package com.cms.audit.enums;

public enum ActionTypeEnum {
    LOG_UPDATE ,STATUS_CHANGE ,   SESSION_EVENT ,RECORD_VIEWED,
    FILE_ACCESS ,SECURITY_INCIDENT, COMMUNICATION_SENT,
    SYSTEM_ERROR , AUDIT_lOG_ACCESS, PORTAL_ACTIVITY;
}
